server:
  port: 8083
spring:
  application:
    name: employee-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DB_URL_EMPLOYEE}
    username: ${user}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    from: ${EMAIL_FROM}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

          # 🔥 IMPORTANT (timeout fixes)
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 30000

        debug: false
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  jackson:
    time-zone: Europe/Vilnius
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
external:
  auth:
    internal-base: http://auth-service:8081

supabase:
  url: ${SUPABASE_URL}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}
  bucket: ${SUPABASE_BUCKET}
  award-bucket: ${SUPABASE_BUCKET}
upload:
  max-bytes: 5242880
jwt:
  secret: ${JWT_SECRET}
internal:
  api:
    key: ${INTERNAL_API_KEY:K3y!9xR7zTq2Lp8}

# push related
push:
  expo:
    api: https://exp.host/--/api/v2/push/send

frontend:
  base-url: https://skavosystem.com